---
- name: Detect compose edition
  ansible.builtin.include_tasks:
    file: detect.ansible.yml
  when: docker_deploy_compose_command == ""

- name: Set compose command
  ansible.builtin.set_fact:
    docker_deploy_command: "{{ docker_deploy_compose_command }}"
  when: docker_deploy_compose_command != ""

- name: Deploy docker stack
  ansible.builtin.include_tasks:
    file: up.ansible.yml
  when: docker_deploy_state | lower == "present"

- name: Remove docker stack
  ansible.builtin.include_tasks:
    file: down.ansible.yml
  when: docker_deploy_state | lower == "absent"
